### ISSUE TITLE
Code Quality

### ISSUE THREAD

**Issue by AlFasGD** [polusgg/Town-Of-Us#112]
Having taken a look at the code, I found several places where its quality can be improved, aside from just indentation alone. Do you accept such contributions and will the changes be accepted if slight modifications are made that could also improve performance at the end?

**Comment by YetAnotherScrub** [comment]
Is performance a concern? It's not as if the game is going to suffer due to lack of resources. Changing things for no benefit doesn't seem like a great idea. Just risks bugs.
Of course if there are correctness issues or something that can improve the network responsiveness that's not a bad idea. Idk if the owner is taking changes like that though.
