### ISSUE TITLE
Feature Request: Revote modifier

### ISSUE THREAD

**Issue by TonyGamer** [polusgg/Town-Of-Us#178]
It might be interesting to have a modifier which allows someone to vote for someone, then be able to change their vote later as more information is revealed. It could be unlimited revotes or limited based on a setting. This feature might also be nice to have as a setting to allow everyone to change their vote instead of having a modifier for it.

**Comment by Eddiemate** [comment]
I don't really think a revote modifier/system would be great, since it just means that you or everyone else can vote early, someone says some damning evidence you could've waited to hear before voting, then just switch votes. The only use I can see is a niche case where the Jester admits to being Jester right before they get voted, and you change your vote so the vote ties or someone else gets voted out. It's practically useless otherwise.

**Comment by ProteinGolem** [comment]
This would ruin vote trolling ;(
