### ISSUE TITLE
Is Town of us a virus?

### ISSUE THREAD

**Issue by pokeyjojo** [polusgg/Town-Of-Us#180]
i'm sure that town of us is safe but on virustotal an antivirus called MaxSecure is flagging it as a Trojan.Malware.300983.susgen is it safe? although i've never heard of MaxSecure before i want to make sure i also don't know how to look for malware in a github repo so could anyone smart let me know?

**Comment by teagan1712simp** [comment]
How do u play it

**Comment by TwilightZebby** [comment]
@teagan1712simp There is literally a guide on [the README](https://github.com/slushiegoose/Town-Of-Us#installation-guide-steam), just scroll down on the main GitHub page for this Repro

**Comment by kotyk7** [comment]
this is a bait lol

"susgen"

**Comment by Oshroth** [comment]
@kotyk7 That's literally what Virus Total says: https://www.virustotal.com/gui/file/cae318393e89828c8b03269914bbc7ed962de0813f8e385942f550293f147432/detection
> Cylance - **Unsafe**
> MaxSecure - **Trojan.Malware.300983.susgen**
> Panda - **Trj/GdSda.A**
> Zillya - **Trojan.GenericKD.Win32.6894**

**Comment by ubiquish** [comment]
> i'm sure that town of us is safe but on virustotal an antivirus called MaxSecure is flagging it as a Trojan.Malware.300983.susgen is it safe? although i've never heard of MaxSecure before i want to make sure i also don't know how to look for malware in a github repo so could anyone smart let me know?

The reason TOU was marked this way by your virus scanner was likely because it is a mod.  As you start to play other game mods, you'll likely learn that almost any tool or program that modifies game code (to accomplish one thing or another) is going to get falsely flagged that way.

The virus scanners have no (simple) way to tell the difference between something that is screwing around with a program behind your back -- versus, in this example, a program that you've downloaded specifically because you WANT it to modify a program.   

So no, it's not a virus.  Is it modifying files on your PC?  Yes, absolutely.  

Did you explicitly download it in order to do exactly that?  Again, yes, absolutely.
