### ISSUE TITLE
New Update not compatible

### ISSUE THREAD

**Issue by leonel1711** [polusgg/Town-Of-Us#23]
Mod isn´t compatible with the new Update.

**Comment by ericknio** [comment]
they will do an update, just wait

**Comment by 1-alex98** [comment]
So the original among loads? Just want to know if that's the issue I have as well

**Comment by Deathzac** [comment]
I've tried **everything**. Uninstalling the mod, veryfing game files, uninstalling the game, etc... 
Nothing works which means I miss out on playing with people.
It seems that for **some** people it is working, and it did once for me, but not anymore. 
It probably is because of the new patch I'd suppose but its annoying.
It'd be good to have it fixed **ASAP**! :)
Thank you ^^

**Comment by manniL** [comment]
Workaround until the update is there: Simply don't update among us. There are various guides on the web how to "downgrade " again btw.

**Comment by Erumeldor** [comment]
Workaround seems to be broken since today. So there is no way to play (any) mods currently. So I would love to see a fix for the new version :)
