### ISSUE TITLE
(updated)Imposter role - Gunslinger

### ISSUE THREAD

**Issue by pxxm69** [polusgg/Town-Of-Us#235]
Just like normal imposter but they won't teleport to the target when they press kill.

Extra:
-The Gunslinger won't be affected by  the diseased.
-The medic can't identify the killer at all. The only thing they know is the victim has been shot.

**Comment by Ajama11** [comment]
Every imposter role needs to have some sort of caveat to not just be "Normal Imposter but strictly better", so here's my proposal:  

After killing someone (or shooting a Medic shield), they need to use the Reload button to be able to kill again. Reloading drops an empty bullet shell on the ground that everyone can see (and potentially even when not in vision range, like Miner's custom vents).

Another possible caveat is an audible gunshot rings out within a certain range. However, I feel that this caveat is too much of a drawback. It completely eliminates speculation between Sheriff Misfire, a failed Shifting, and a Swooper, and it can hard-clear other people from the kill because everyone near it would know exactly when the body dropped (as well as the fact that someone just died and that they should try to find the body). It would also need some sort of visual component so that deaf players and players who don't play with game audio on are not at a disadvantage.

**Comment by pxxm69** [comment]
Finally!! Someone who talk to me.

Thanks for complete my ideas. But I don't think any ideas of mine will be added to the game. I'm here just to talk.

Old Gunslinger abilities (before I change to this one)

-kill and not teleport to the body(confusing people who stay together)
-medic can't identify you
-won't be affected by the diseased
-Gunslinger's kill distance is as long as their vision

And old way to balance(deleted)

-gunslinger's vision will be affected by the light sabotage.(maybe they should have crewmate vision)
-they can only kill in their vision

Would you mind if I want you to comment about my other ideas
